### ISSUE TITLE
set_ip_transparent is not detected on target aarch64-linux-android 

### ISSUE THREAD

**Issue by Arlen22** [rust-lang/socket2#317]
I can't figure out what's going on, as this is my first rust project. I'm trying to call set_ip_transparent on a socket but it gives me the error "no method named `set_ip_transparent` found for struct `Socket` in the current scope".

```toml
# config.toml
[build]
target="aarch64-linux-android"
```

```rs
// main.rs
    let tcpsock =
        Socket::new(Domain::IPV4, Type::STREAM, None)
            .expect("Failed to create new socket object");
    tcpsock.bind(&SockAddr::from(addr))
        .expect(&format!("failed to bind socket to {}", addr)[..]);
    tcpsock.set_ip_transparent();
```
```toml
# Cargo.toml
[package]
name = "tproxy"
version = "0.0.1"
edition = "2021"
[dependencies]
socket2 = { version = "0.4.4", features = ["all"] }
clap = { version = "3.2.6", features = ["derive"] }
```
